// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateInviteApiV1InvitesPostData, CreateInviteApiV1InvitesPostErrors, CreateInviteApiV1InvitesPostResponses, GetDiagnosticApiV1DiagnosticsInstrumentIdGetData, GetDiagnosticApiV1DiagnosticsInstrumentIdGetErrors, GetDiagnosticApiV1DiagnosticsInstrumentIdGetResponses, GetExamApiV1ExamsExamIdGetData, GetExamApiV1ExamsExamIdGetErrors, GetExamApiV1ExamsExamIdGetResponses, GetMyProgressApiV1ProgressGetData, GetMyProgressApiV1ProgressGetResponses, GetUserProgressApiV1UsersUserIdProgressGetData, GetUserProgressApiV1UsersUserIdProgressGetErrors, GetUserProgressApiV1UsersUserIdProgressGetResponses, ListDiagnosticsApiV1DiagnosticsGetData, ListDiagnosticsApiV1DiagnosticsGetResponses, ListExamsApiV1ExamsGetData, ListExamsApiV1ExamsGetErrors, ListExamsApiV1ExamsGetResponses, LivenessHealthLiveGetData, LivenessHealthLiveGetResponses, LoginApiV1AuthLoginPostData, LoginApiV1AuthLoginPostErrors, LoginApiV1AuthLoginPostResponses, LogoutApiV1AuthLogoutPostData, LogoutApiV1AuthLogoutPostResponses, MeApiV1AuthMeGetData, MeApiV1AuthMeGetResponses, ReadinessHealthReadyGetData, ReadinessHealthReadyGetErrors, ReadinessHealthReadyGetResponses, RegisterApiV1AuthRegisterPostData, RegisterApiV1AuthRegisterPostErrors, RegisterApiV1AuthRegisterPostResponses, StartupHealthStartupGetData, StartupHealthStartupGetResponses, SubmitDiagnosticApiV1DiagnosticsInstrumentIdAttemptsPostData, SubmitDiagnosticApiV1DiagnosticsInstrumentIdAttemptsPostErrors, SubmitDiagnosticApiV1DiagnosticsInstrumentIdAttemptsPostResponses, SubmitExamApiV1ExamsExamIdAttemptsPostData, SubmitExamApiV1ExamsExamIdAttemptsPostErrors, SubmitExamApiV1ExamsExamIdAttemptsPostResponses, ValidateInviteApiV1AuthInvitesTokenGetData, ValidateInviteApiV1AuthInvitesTokenGetErrors, ValidateInviteApiV1AuthInvitesTokenGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Liveness probe
 *
 * Indicates if the application is running. Used by Kubernetes liveness probe.
 */
export const livenessHealthLiveGet = <ThrowOnError extends boolean = false>(options?: Options<LivenessHealthLiveGetData, ThrowOnError>): RequestResult<LivenessHealthLiveGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<LivenessHealthLiveGetResponses, unknown, ThrowOnError>({ url: '/health/live', ...options });

/**
 * Readiness probe
 *
 * Checks if the application can serve traffic. Used by Kubernetes readiness probe.
 */
export const readinessHealthReadyGet = <ThrowOnError extends boolean = false>(options?: Options<ReadinessHealthReadyGetData, ThrowOnError>): RequestResult<ReadinessHealthReadyGetResponses, ReadinessHealthReadyGetErrors, ThrowOnError> => (options?.client ?? client).get<ReadinessHealthReadyGetResponses, ReadinessHealthReadyGetErrors, ThrowOnError>({ url: '/health/ready', ...options });

/**
 * Startup probe
 *
 * Indicates if the application has completed startup. Used by Kubernetes startup probe.
 */
export const startupHealthStartupGet = <ThrowOnError extends boolean = false>(options?: Options<StartupHealthStartupGetData, ThrowOnError>): RequestResult<StartupHealthStartupGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<StartupHealthStartupGetResponses, unknown, ThrowOnError>({ url: '/health/startup', ...options });

/**
 * Login
 *
 * Authenticate and start a session.
 *
 * Login attempts are rate-limited per email to mitigate credential stuffing.
 *
 * Args:
 * payload: The login credentials.
 * response: The response (the session cookie is set on it).
 * db: The request-scoped database session.
 *
 * Returns:
 * The authenticated user.
 *
 * Raises:
 * AuthenticationError: On bad credentials or when rate-limited.
 */
export const loginApiV1AuthLoginPost = <ThrowOnError extends boolean = false>(options: Options<LoginApiV1AuthLoginPostData, ThrowOnError>): RequestResult<LoginApiV1AuthLoginPostResponses, LoginApiV1AuthLoginPostErrors, ThrowOnError> => (options.client ?? client).post<LoginApiV1AuthLoginPostResponses, LoginApiV1AuthLoginPostErrors, ThrowOnError>({
    url: '/api/v1/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Logout
 *
 * End the current session, if any.
 *
 * Always clears the cookie and returns 204, even if no valid session is present,
 * so logout is idempotent.
 *
 * Args:
 * request: The incoming request (for the session cookie).
 * response: The response (the cookie is cleared on it).
 * db: The request-scoped database session.
 *
 * Returns:
 * An empty 204 response.
 */
export const logoutApiV1AuthLogoutPost = <ThrowOnError extends boolean = false>(options?: Options<LogoutApiV1AuthLogoutPostData, ThrowOnError>): RequestResult<LogoutApiV1AuthLogoutPostResponses, unknown, ThrowOnError> => (options?.client ?? client).post<LogoutApiV1AuthLogoutPostResponses, unknown, ThrowOnError>({ url: '/api/v1/auth/logout', ...options });

/**
 * Me
 *
 * Return the currently authenticated user.
 *
 * Args:
 * user: The authenticated user (from the session cookie).
 *
 * Returns:
 * The current user.
 */
export const meApiV1AuthMeGet = <ThrowOnError extends boolean = false>(options?: Options<MeApiV1AuthMeGetData, ThrowOnError>): RequestResult<MeApiV1AuthMeGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<MeApiV1AuthMeGetResponses, unknown, ThrowOnError>({ url: '/api/v1/auth/me', ...options });

/**
 * Register
 *
 * Redeem an invite, create the account, and start a session.
 *
 * Args:
 * payload: The invite token, display name, and chosen password.
 * response: The response (the session cookie is set on it).
 * db: The request-scoped database session.
 *
 * Returns:
 * The newly created user.
 *
 * Raises:
 * ValidationError: If the invite is invalid/expired or the email is taken.
 */
export const registerApiV1AuthRegisterPost = <ThrowOnError extends boolean = false>(options: Options<RegisterApiV1AuthRegisterPostData, ThrowOnError>): RequestResult<RegisterApiV1AuthRegisterPostResponses, RegisterApiV1AuthRegisterPostErrors, ThrowOnError> => (options.client ?? client).post<RegisterApiV1AuthRegisterPostResponses, RegisterApiV1AuthRegisterPostErrors, ThrowOnError>({
    url: '/api/v1/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Validate Invite
 *
 * Validate an invite token without redeeming it.
 *
 * Args:
 * token: The raw invite token from the invite link.
 * db: The request-scoped database session.
 *
 * Returns:
 * Whether the token is valid and, if so, the email and role it grants.
 */
export const validateInviteApiV1AuthInvitesTokenGet = <ThrowOnError extends boolean = false>(options: Options<ValidateInviteApiV1AuthInvitesTokenGetData, ThrowOnError>): RequestResult<ValidateInviteApiV1AuthInvitesTokenGetResponses, ValidateInviteApiV1AuthInvitesTokenGetErrors, ThrowOnError> => (options.client ?? client).get<ValidateInviteApiV1AuthInvitesTokenGetResponses, ValidateInviteApiV1AuthInvitesTokenGetErrors, ThrowOnError>({ url: '/api/v1/auth/invites/{token}', ...options });

/**
 * Create Invite
 *
 * Mint a one-time invite token (coach/admin only).
 *
 * The raw token is returned exactly once for the issuer to share; only its hash
 * is stored.
 *
 * Args:
 * payload: The invitee email and role to grant.
 * staff: The authenticated coach/admin issuing the invite.
 * db: The request-scoped database session.
 *
 * Returns:
 * The created invite including the one-time raw token.
 *
 * Raises:
 * ValidationError: If the requested role is invalid.
 */
export const createInviteApiV1InvitesPost = <ThrowOnError extends boolean = false>(options: Options<CreateInviteApiV1InvitesPostData, ThrowOnError>): RequestResult<CreateInviteApiV1InvitesPostResponses, CreateInviteApiV1InvitesPostErrors, ThrowOnError> => (options.client ?? client).post<CreateInviteApiV1InvitesPostResponses, CreateInviteApiV1InvitesPostErrors, ThrowOnError>({
    url: '/api/v1/invites',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Exams
 *
 * List available exams, optionally filtered by contest.
 *
 * Args:
 * _user: The authenticated user (auth required).
 * db: The request-scoped database session.
 * contest: Optional contest filter (e.g. ``AMC 10``).
 *
 * Returns:
 * Exam summaries.
 */
export const listExamsApiV1ExamsGet = <ThrowOnError extends boolean = false>(options?: Options<ListExamsApiV1ExamsGetData, ThrowOnError>): RequestResult<ListExamsApiV1ExamsGetResponses, ListExamsApiV1ExamsGetErrors, ThrowOnError> => (options?.client ?? client).get<ListExamsApiV1ExamsGetResponses, ListExamsApiV1ExamsGetErrors, ThrowOnError>({ url: '/api/v1/exams', ...options });

/**
 * Get Exam
 *
 * Return an exam and its problems, without the answer key.
 *
 * Args:
 * exam_id: The exam id.
 * _user: The authenticated user (auth required).
 * db: The request-scoped database session.
 *
 * Returns:
 * The exam detail with key-free problems.
 *
 * Raises:
 * ResourceNotFoundError: If the exam does not exist.
 */
export const getExamApiV1ExamsExamIdGet = <ThrowOnError extends boolean = false>(options: Options<GetExamApiV1ExamsExamIdGetData, ThrowOnError>): RequestResult<GetExamApiV1ExamsExamIdGetResponses, GetExamApiV1ExamsExamIdGetErrors, ThrowOnError> => (options.client ?? client).get<GetExamApiV1ExamsExamIdGetResponses, GetExamApiV1ExamsExamIdGetErrors, ThrowOnError>({ url: '/api/v1/exams/{exam_id}', ...options });

/**
 * List Diagnostics
 *
 * List available diagnostic instruments.
 *
 * Args:
 * _user: The authenticated user (auth required).
 * db: The request-scoped database session.
 *
 * Returns:
 * Diagnostic summaries.
 */
export const listDiagnosticsApiV1DiagnosticsGet = <ThrowOnError extends boolean = false>(options?: Options<ListDiagnosticsApiV1DiagnosticsGetData, ThrowOnError>): RequestResult<ListDiagnosticsApiV1DiagnosticsGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListDiagnosticsApiV1DiagnosticsGetResponses, unknown, ThrowOnError>({ url: '/api/v1/diagnostics', ...options });

/**
 * Get Diagnostic
 *
 * Return a diagnostic instrument and its items, without answers.
 *
 * Args:
 * instrument_id: The instrument slug.
 * _user: The authenticated user (auth required).
 * db: The request-scoped database session.
 *
 * Returns:
 * The instrument detail with key-free items.
 *
 * Raises:
 * ResourceNotFoundError: If the instrument does not exist.
 */
export const getDiagnosticApiV1DiagnosticsInstrumentIdGet = <ThrowOnError extends boolean = false>(options: Options<GetDiagnosticApiV1DiagnosticsInstrumentIdGetData, ThrowOnError>): RequestResult<GetDiagnosticApiV1DiagnosticsInstrumentIdGetResponses, GetDiagnosticApiV1DiagnosticsInstrumentIdGetErrors, ThrowOnError> => (options.client ?? client).get<GetDiagnosticApiV1DiagnosticsInstrumentIdGetResponses, GetDiagnosticApiV1DiagnosticsInstrumentIdGetErrors, ThrowOnError>({ url: '/api/v1/diagnostics/{instrument_id}', ...options });

/**
 * Submit Exam
 *
 * Grade and store an exam submission, returning the reviewed result.
 *
 * Args:
 * exam_id: The exam being submitted.
 * payload: The student's answers, flags, and time used.
 * user: The authenticated submitting user.
 * db: The request-scoped database session.
 *
 * Returns:
 * The graded result, including the per-problem review with answers.
 *
 * Raises:
 * ResourceNotFoundError: If the exam does not exist.
 */
export const submitExamApiV1ExamsExamIdAttemptsPost = <ThrowOnError extends boolean = false>(options: Options<SubmitExamApiV1ExamsExamIdAttemptsPostData, ThrowOnError>): RequestResult<SubmitExamApiV1ExamsExamIdAttemptsPostResponses, SubmitExamApiV1ExamsExamIdAttemptsPostErrors, ThrowOnError> => (options.client ?? client).post<SubmitExamApiV1ExamsExamIdAttemptsPostResponses, SubmitExamApiV1ExamsExamIdAttemptsPostErrors, ThrowOnError>({
    url: '/api/v1/exams/{exam_id}/attempts',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Submit Diagnostic
 *
 * Grade and store a diagnostic submission, returning the verdict.
 *
 * Auto-graded items are checked server-side; manual items use the student's
 * self-mark. The verdict is recomputed from the instrument's grading config.
 *
 * Args:
 * instrument_id: The instrument being submitted.
 * payload: The student's responses, self-marks, and elapsed time.
 * user: The authenticated submitting user.
 * db: The request-scoped database session.
 *
 * Returns:
 * The graded result, including verdict and per-item review.
 *
 * Raises:
 * ResourceNotFoundError: If the instrument does not exist.
 */
export const submitDiagnosticApiV1DiagnosticsInstrumentIdAttemptsPost = <ThrowOnError extends boolean = false>(options: Options<SubmitDiagnosticApiV1DiagnosticsInstrumentIdAttemptsPostData, ThrowOnError>): RequestResult<SubmitDiagnosticApiV1DiagnosticsInstrumentIdAttemptsPostResponses, SubmitDiagnosticApiV1DiagnosticsInstrumentIdAttemptsPostErrors, ThrowOnError> => (options.client ?? client).post<SubmitDiagnosticApiV1DiagnosticsInstrumentIdAttemptsPostResponses, SubmitDiagnosticApiV1DiagnosticsInstrumentIdAttemptsPostErrors, ThrowOnError>({
    url: '/api/v1/diagnostics/{instrument_id}/attempts',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get My Progress
 *
 * Return the authenticated user's progress and recommendation.
 *
 * Args:
 * user: The authenticated user.
 * db: The request-scoped database session.
 *
 * Returns:
 * The user's history and synthesized recommendation.
 */
export const getMyProgressApiV1ProgressGet = <ThrowOnError extends boolean = false>(options?: Options<GetMyProgressApiV1ProgressGetData, ThrowOnError>): RequestResult<GetMyProgressApiV1ProgressGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetMyProgressApiV1ProgressGetResponses, unknown, ThrowOnError>({ url: '/api/v1/progress', ...options });

/**
 * Get User Progress
 *
 * Return a specific user's progress (self, or any user for staff).
 *
 * Args:
 * user_id: The target user's id.
 * viewer: The authenticated requesting user.
 * db: The request-scoped database session.
 *
 * Returns:
 * The target user's history and synthesized recommendation.
 *
 * Raises:
 * AuthorizationError: If a non-staff viewer requests another user's data.
 * ResourceNotFoundError: If the target user does not exist.
 */
export const getUserProgressApiV1UsersUserIdProgressGet = <ThrowOnError extends boolean = false>(options: Options<GetUserProgressApiV1UsersUserIdProgressGetData, ThrowOnError>): RequestResult<GetUserProgressApiV1UsersUserIdProgressGetResponses, GetUserProgressApiV1UsersUserIdProgressGetErrors, ThrowOnError> => (options.client ?? client).get<GetUserProgressApiV1UsersUserIdProgressGetResponses, GetUserProgressApiV1UsersUserIdProgressGetErrors, ThrowOnError>({ url: '/api/v1/users/{user_id}/progress', ...options });
