// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from '@hey-api/client-fetch';
import type { LivenessHealthLiveGetError, LivenessHealthLiveGetResponse, ReadinessHealthReadyGetError, ReadinessHealthReadyGetResponse, StartupHealthStartupGetError, StartupHealthStartupGetResponse, LoginApiV1AuthLoginPostData, LoginApiV1AuthLoginPostError, LoginApiV1AuthLoginPostResponse, LogoutApiV1AuthLogoutPostError, LogoutApiV1AuthLogoutPostResponse, MeApiV1AuthMeGetError, MeApiV1AuthMeGetResponse, RegisterApiV1AuthRegisterPostData, RegisterApiV1AuthRegisterPostError, RegisterApiV1AuthRegisterPostResponse, ValidateInviteApiV1AuthInvitesTokenGetData, ValidateInviteApiV1AuthInvitesTokenGetError, ValidateInviteApiV1AuthInvitesTokenGetResponse, CreateInviteApiV1InvitesPostData, CreateInviteApiV1InvitesPostError, CreateInviteApiV1InvitesPostResponse, ListExamsApiV1ExamsGetData, ListExamsApiV1ExamsGetError, ListExamsApiV1ExamsGetResponse, GetExamApiV1ExamsExamIdGetData, GetExamApiV1ExamsExamIdGetError, GetExamApiV1ExamsExamIdGetResponse, ListDiagnosticsApiV1DiagnosticsGetError, ListDiagnosticsApiV1DiagnosticsGetResponse, GetDiagnosticApiV1DiagnosticsInstrumentIdGetData, GetDiagnosticApiV1DiagnosticsInstrumentIdGetError, GetDiagnosticApiV1DiagnosticsInstrumentIdGetResponse, SubmitExamApiV1ExamsExamIdAttemptsPostData, SubmitExamApiV1ExamsExamIdAttemptsPostError, SubmitExamApiV1ExamsExamIdAttemptsPostResponse, SubmitDiagnosticApiV1DiagnosticsInstrumentIdAttemptsPostData, SubmitDiagnosticApiV1DiagnosticsInstrumentIdAttemptsPostError, SubmitDiagnosticApiV1DiagnosticsInstrumentIdAttemptsPostResponse, GetMyProgressApiV1ProgressGetError, GetMyProgressApiV1ProgressGetResponse, GetUserProgressApiV1UsersUserIdProgressGetData, GetUserProgressApiV1UsersUserIdProgressGetError, GetUserProgressApiV1UsersUserIdProgressGetResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Liveness probe
 * Indicates if the application is running. Used by Kubernetes liveness probe.
 */
export const livenessHealthLiveGet = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<LivenessHealthLiveGetResponse, LivenessHealthLiveGetError, ThrowOnError>({
        ...options,
        url: '/health/live'
    });
};

/**
 * Readiness probe
 * Checks if the application can serve traffic. Used by Kubernetes readiness probe.
 */
export const readinessHealthReadyGet = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<ReadinessHealthReadyGetResponse, ReadinessHealthReadyGetError, ThrowOnError>({
        ...options,
        url: '/health/ready'
    });
};

/**
 * Startup probe
 * Indicates if the application has completed startup. Used by Kubernetes startup probe.
 */
export const startupHealthStartupGet = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<StartupHealthStartupGetResponse, StartupHealthStartupGetError, ThrowOnError>({
        ...options,
        url: '/health/startup'
    });
};

/**
 * Login
 * Authenticate and start a session.
 *
 * Login attempts are rate-limited per email to mitigate credential stuffing.
 *
 * Args:
 * payload: The login credentials.
 * response: The response (the session cookie is set on it).
 * db: The request-scoped database session.
 *
 * Returns:
 * The authenticated user.
 *
 * Raises:
 * AuthenticationError: On bad credentials or when rate-limited.
 */
export const loginApiV1AuthLoginPost = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<LoginApiV1AuthLoginPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<LoginApiV1AuthLoginPostResponse, LoginApiV1AuthLoginPostError, ThrowOnError>({
        ...options,
        url: '/api/v1/auth/login'
    });
};

/**
 * Logout
 * End the current session, if any.
 *
 * Always clears the cookie and returns 204, even if no valid session is present,
 * so logout is idempotent.
 *
 * Args:
 * request: The incoming request (for the session cookie).
 * response: The response (the cookie is cleared on it).
 * db: The request-scoped database session.
 *
 * Returns:
 * An empty 204 response.
 */
export const logoutApiV1AuthLogoutPost = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).post<LogoutApiV1AuthLogoutPostResponse, LogoutApiV1AuthLogoutPostError, ThrowOnError>({
        ...options,
        url: '/api/v1/auth/logout'
    });
};

/**
 * Me
 * Return the currently authenticated user.
 *
 * Args:
 * user: The authenticated user (from the session cookie).
 *
 * Returns:
 * The current user.
 */
export const meApiV1AuthMeGet = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<MeApiV1AuthMeGetResponse, MeApiV1AuthMeGetError, ThrowOnError>({
        ...options,
        url: '/api/v1/auth/me'
    });
};

/**
 * Register
 * Redeem an invite, create the account, and start a session.
 *
 * Args:
 * payload: The invite token, display name, and chosen password.
 * response: The response (the session cookie is set on it).
 * db: The request-scoped database session.
 *
 * Returns:
 * The newly created user.
 *
 * Raises:
 * ValidationError: If the invite is invalid/expired or the email is taken.
 */
export const registerApiV1AuthRegisterPost = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<RegisterApiV1AuthRegisterPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<RegisterApiV1AuthRegisterPostResponse, RegisterApiV1AuthRegisterPostError, ThrowOnError>({
        ...options,
        url: '/api/v1/auth/register'
    });
};

/**
 * Validate Invite
 * Validate an invite token without redeeming it.
 *
 * Args:
 * token: The raw invite token from the invite link.
 * db: The request-scoped database session.
 *
 * Returns:
 * Whether the token is valid and, if so, the email and role it grants.
 */
export const validateInviteApiV1AuthInvitesTokenGet = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<ValidateInviteApiV1AuthInvitesTokenGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<ValidateInviteApiV1AuthInvitesTokenGetResponse, ValidateInviteApiV1AuthInvitesTokenGetError, ThrowOnError>({
        ...options,
        url: '/api/v1/auth/invites/{token}'
    });
};

/**
 * Create Invite
 * Mint a one-time invite token (coach/admin only).
 *
 * The raw token is returned exactly once for the issuer to share; only its hash
 * is stored.
 *
 * Args:
 * payload: The invitee email and role to grant.
 * staff: The authenticated coach/admin issuing the invite.
 * db: The request-scoped database session.
 *
 * Returns:
 * The created invite including the one-time raw token.
 *
 * Raises:
 * ValidationError: If the requested role is invalid.
 */
export const createInviteApiV1InvitesPost = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<CreateInviteApiV1InvitesPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateInviteApiV1InvitesPostResponse, CreateInviteApiV1InvitesPostError, ThrowOnError>({
        ...options,
        url: '/api/v1/invites'
    });
};

/**
 * List Exams
 * List available exams, optionally filtered by contest.
 *
 * Args:
 * _user: The authenticated user (auth required).
 * db: The request-scoped database session.
 * contest: Optional contest filter (e.g. ``AMC 10``).
 *
 * Returns:
 * Exam summaries.
 */
export const listExamsApiV1ExamsGet = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<ListExamsApiV1ExamsGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListExamsApiV1ExamsGetResponse, ListExamsApiV1ExamsGetError, ThrowOnError>({
        ...options,
        url: '/api/v1/exams'
    });
};

/**
 * Get Exam
 * Return an exam and its problems, without the answer key.
 *
 * Args:
 * exam_id: The exam id.
 * _user: The authenticated user (auth required).
 * db: The request-scoped database session.
 *
 * Returns:
 * The exam detail with key-free problems.
 *
 * Raises:
 * ResourceNotFoundError: If the exam does not exist.
 */
export const getExamApiV1ExamsExamIdGet = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetExamApiV1ExamsExamIdGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetExamApiV1ExamsExamIdGetResponse, GetExamApiV1ExamsExamIdGetError, ThrowOnError>({
        ...options,
        url: '/api/v1/exams/{exam_id}'
    });
};

/**
 * List Diagnostics
 * List available diagnostic instruments.
 *
 * Args:
 * _user: The authenticated user (auth required).
 * db: The request-scoped database session.
 *
 * Returns:
 * Diagnostic summaries.
 */
export const listDiagnosticsApiV1DiagnosticsGet = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<ListDiagnosticsApiV1DiagnosticsGetResponse, ListDiagnosticsApiV1DiagnosticsGetError, ThrowOnError>({
        ...options,
        url: '/api/v1/diagnostics'
    });
};

/**
 * Get Diagnostic
 * Return a diagnostic instrument and its items, without answers.
 *
 * Args:
 * instrument_id: The instrument slug.
 * _user: The authenticated user (auth required).
 * db: The request-scoped database session.
 *
 * Returns:
 * The instrument detail with key-free items.
 *
 * Raises:
 * ResourceNotFoundError: If the instrument does not exist.
 */
export const getDiagnosticApiV1DiagnosticsInstrumentIdGet = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetDiagnosticApiV1DiagnosticsInstrumentIdGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetDiagnosticApiV1DiagnosticsInstrumentIdGetResponse, GetDiagnosticApiV1DiagnosticsInstrumentIdGetError, ThrowOnError>({
        ...options,
        url: '/api/v1/diagnostics/{instrument_id}'
    });
};

/**
 * Submit Exam
 * Grade and store an exam submission, returning the reviewed result.
 *
 * Args:
 * exam_id: The exam being submitted.
 * payload: The student's answers, flags, and time used.
 * user: The authenticated submitting user.
 * db: The request-scoped database session.
 *
 * Returns:
 * The graded result, including the per-problem review with answers.
 *
 * Raises:
 * ResourceNotFoundError: If the exam does not exist.
 */
export const submitExamApiV1ExamsExamIdAttemptsPost = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<SubmitExamApiV1ExamsExamIdAttemptsPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<SubmitExamApiV1ExamsExamIdAttemptsPostResponse, SubmitExamApiV1ExamsExamIdAttemptsPostError, ThrowOnError>({
        ...options,
        url: '/api/v1/exams/{exam_id}/attempts'
    });
};

/**
 * Submit Diagnostic
 * Grade and store a diagnostic submission, returning the verdict.
 *
 * Auto-graded items are checked server-side; manual items use the student's
 * self-mark. The verdict is recomputed from the instrument's grading config.
 *
 * Args:
 * instrument_id: The instrument being submitted.
 * payload: The student's responses, self-marks, and elapsed time.
 * user: The authenticated submitting user.
 * db: The request-scoped database session.
 *
 * Returns:
 * The graded result, including verdict and per-item review.
 *
 * Raises:
 * ResourceNotFoundError: If the instrument does not exist.
 */
export const submitDiagnosticApiV1DiagnosticsInstrumentIdAttemptsPost = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<SubmitDiagnosticApiV1DiagnosticsInstrumentIdAttemptsPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<SubmitDiagnosticApiV1DiagnosticsInstrumentIdAttemptsPostResponse, SubmitDiagnosticApiV1DiagnosticsInstrumentIdAttemptsPostError, ThrowOnError>({
        ...options,
        url: '/api/v1/diagnostics/{instrument_id}/attempts'
    });
};

/**
 * Get My Progress
 * Return the authenticated user's progress and recommendation.
 *
 * Args:
 * user: The authenticated user.
 * db: The request-scoped database session.
 *
 * Returns:
 * The user's history and synthesized recommendation.
 */
export const getMyProgressApiV1ProgressGet = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<GetMyProgressApiV1ProgressGetResponse, GetMyProgressApiV1ProgressGetError, ThrowOnError>({
        ...options,
        url: '/api/v1/progress'
    });
};

/**
 * Get User Progress
 * Return a specific user's progress (self, or any user for staff).
 *
 * Args:
 * user_id: The target user's id.
 * viewer: The authenticated requesting user.
 * db: The request-scoped database session.
 *
 * Returns:
 * The target user's history and synthesized recommendation.
 *
 * Raises:
 * AuthorizationError: If a non-staff viewer requests another user's data.
 * ResourceNotFoundError: If the target user does not exist.
 */
export const getUserProgressApiV1UsersUserIdProgressGet = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetUserProgressApiV1UsersUserIdProgressGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetUserProgressApiV1UsersUserIdProgressGetResponse, GetUserProgressApiV1UsersUserIdProgressGetError, ThrowOnError>({
        ...options,
        url: '/api/v1/users/{user_id}/progress'
    });
};
