// This file is auto-generated by @hey-api/openapi-ts

/**
 * A diagnostic instrument with its items, served before submission.
 */
export type DiagnosticDetail = {
    id: string;
    course: string;
    kind: string;
    role: string;
    instructions: string;
    items: Array<DiagnosticItemRead>;
};

/**
 * A diagnostic item served before submission (no answer key).
 *
 * ``manual`` is exposed so the runner knows which items are self-marked;
 * ``answer`` / ``v`` / ``accept`` are intentionally absent.
 */
export type DiagnosticItemRead = {
    id: string;
    section_title: string;
    label: string;
    prompt: string;
    manual: boolean;
};

/**
 * One item's post-submission review (answer revealed here).
 */
export type DiagnosticItemReview = {
    item_id: string;
    correct: boolean;
    manual: boolean;
    answer: string;
};

/**
 * The graded result of a diagnostic submission.
 */
export type DiagnosticResultResponse = {
    attempt_id: string;
    passed: boolean;
    verdict: string;
    correct: number;
    total: number;
    summary: string;
    group_scores?: {
        [key: string]: (number);
    };
    review?: Array<DiagnosticItemReview>;
};

/**
 * A student's diagnostic submission.
 *
 * Attributes:
 * responses: Item id -> raw typed answer (for auto-graded items).
 * marks: Item id -> bool, the student's self-marks for manual items.
 * elapsed_sec: Seconds spent before submission.
 */
export type DiagnosticSubmission = {
    responses?: {
        [key: string]: (string);
    };
    marks?: {
        [key: string]: (boolean);
    };
    elapsed_sec?: number;
};

/**
 * A diagnostic instrument in a catalog listing (no items).
 */
export type DiagnosticSummary = {
    id: string;
    course: string;
    kind: string;
    role: string;
};

/**
 * An exam with its problems, served before submission (no answer key).
 */
export type ExamDetail = {
    id: string;
    contest: string;
    year: number;
    variant: string;
    duration_sec: number;
    score_mode: string;
    num_problems: number;
    voided: Array<(number)>;
    problems: Array<ProblemRead>;
};

/**
 * The graded result of an exam submission.
 */
export type ExamResultResponse = {
    attempt_id: string;
    score: number;
    max_score: number;
    correct: number;
    wrong: number;
    blank: number;
    review: Array<ReviewItemResponse>;
};

/**
 * A student's exam submission.
 */
export type ExamSubmission = {
    answers: Array<(string | null)>;
    flags?: Array<(boolean)>;
    time_used_sec?: number;
};

/**
 * An exam in a catalog listing (no problems).
 */
export type ExamSummary = {
    id: string;
    contest: string;
    year: number;
    variant: string;
    duration_sec: number;
    score_mode: string;
    num_problems: number;
};

/**
 * Health check response model.
 */
export type HealthStatus = {
    /**
     * Overall status: ok, degraded, or error
     */
    status: string;
    /**
     * Unix timestamp
     */
    timestamp?: number;
    /**
     * Application uptime in seconds
     */
    uptime_seconds: number;
    /**
     * Application version
     */
    version?: string;
    python_version?: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * The freshly minted invite; ``token`` is shown exactly once.
 */
export type InviteCreatedResponse = {
    token: string;
    email: string;
    role: string;
};

/**
 * Request to mint a one-time invite (coach/admin only).
 */
export type InviteCreateRequest = {
    email: string;
    role?: string;
};

/**
 * Public validation result for an invite token.
 */
export type InviteValidationResponse = {
    valid: boolean;
    email?: (string | null);
    role?: (string | null);
};

/**
 * Credentials for starting a session.
 */
export type LoginRequest = {
    email: string;
    password: string;
};

/**
 * A problem as served before submission.
 *
 * Note the deliberate absence of any ``correct_answer`` field.
 */
export type ProblemRead = {
    number: number;
    render_mode: string;
    body_latex?: (string | null);
    image_path?: (string | null);
    choices?: (Array<{
    [key: string]: unknown;
}> | null);
};

/**
 * A user's combined progress and recommendation.
 */
export type ProgressResponse = {
    test_attempts: Array<unknown>;
    diagnostic_attempts: Array<unknown>;
    recommendation_course: (string | null);
    recommendation_reason: string;
    unlocked_by_amc?: Array<(string)>;
    algebra_warning?: (string | null);
};

/**
 * Individual dependency check result.
 */
export type ReadinessCheck = {
    /**
     * Dependency name
     */
    name: string;
    /**
     * Check passed
     */
    status: boolean;
    /**
     * Check latency in milliseconds
     */
    latency_ms?: (number | null);
    /**
     * Error message if failed
     */
    error?: (string | null);
};

/**
 * Readiness check response with dependency details.
 */
export type ReadinessStatus = {
    /**
     * Overall status: ok, degraded, or error
     */
    status: string;
    /**
     * Unix timestamp
     */
    timestamp?: number;
    /**
     * Application uptime in seconds
     */
    uptime_seconds: number;
    /**
     * Application version
     */
    version?: string;
    python_version?: string;
    /**
     * Individual dependency checks
     */
    checks?: {
        [key: string]: ReadinessCheck;
    };
};

/**
 * Invite redemption: set a password and create the account.
 */
export type RegisterRequest = {
    token: string;
    display_name: string;
    password: string;
};

/**
 * One problem's post-submission review (answer key revealed here).
 */
export type ReviewItemResponse = {
    n: number;
    your: (string | null);
    correct: string;
    ok: boolean;
    voided: boolean;
};

/**
 * A user, safe to return to the authenticated client.
 */
export type UserResponse = {
    id: string;
    email: string;
    display_name: string;
    role: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type LivenessHealthLiveGetResponse = (HealthStatus);

export type LivenessHealthLiveGetError = unknown;

export type ReadinessHealthReadyGetResponse = (ReadinessStatus);

export type ReadinessHealthReadyGetError = (unknown);

export type StartupHealthStartupGetResponse = (HealthStatus);

export type StartupHealthStartupGetError = unknown;

export type LoginApiV1AuthLoginPostData = {
    body: LoginRequest;
};

export type LoginApiV1AuthLoginPostResponse = (UserResponse);

export type LoginApiV1AuthLoginPostError = (HTTPValidationError);

export type LogoutApiV1AuthLogoutPostResponse = (void);

export type LogoutApiV1AuthLogoutPostError = unknown;

export type MeApiV1AuthMeGetResponse = (UserResponse);

export type MeApiV1AuthMeGetError = unknown;

export type RegisterApiV1AuthRegisterPostData = {
    body: RegisterRequest;
};

export type RegisterApiV1AuthRegisterPostResponse = (UserResponse);

export type RegisterApiV1AuthRegisterPostError = (HTTPValidationError);

export type ValidateInviteApiV1AuthInvitesTokenGetData = {
    path: {
        token: string;
    };
};

export type ValidateInviteApiV1AuthInvitesTokenGetResponse = (InviteValidationResponse);

export type ValidateInviteApiV1AuthInvitesTokenGetError = (HTTPValidationError);

export type CreateInviteApiV1InvitesPostData = {
    body: InviteCreateRequest;
};

export type CreateInviteApiV1InvitesPostResponse = (InviteCreatedResponse);

export type CreateInviteApiV1InvitesPostError = (HTTPValidationError);

export type ListExamsApiV1ExamsGetData = {
    query?: {
        contest?: (string | null);
    };
};

export type ListExamsApiV1ExamsGetResponse = (Array<ExamSummary>);

export type ListExamsApiV1ExamsGetError = (HTTPValidationError);

export type GetExamApiV1ExamsExamIdGetData = {
    path: {
        exam_id: string;
    };
};

export type GetExamApiV1ExamsExamIdGetResponse = (ExamDetail);

export type GetExamApiV1ExamsExamIdGetError = (HTTPValidationError);

export type ListDiagnosticsApiV1DiagnosticsGetResponse = (Array<DiagnosticSummary>);

export type ListDiagnosticsApiV1DiagnosticsGetError = unknown;

export type GetDiagnosticApiV1DiagnosticsInstrumentIdGetData = {
    path: {
        instrument_id: string;
    };
};

export type GetDiagnosticApiV1DiagnosticsInstrumentIdGetResponse = (DiagnosticDetail);

export type GetDiagnosticApiV1DiagnosticsInstrumentIdGetError = (HTTPValidationError);

export type SubmitExamApiV1ExamsExamIdAttemptsPostData = {
    body: ExamSubmission;
    path: {
        exam_id: string;
    };
};

export type SubmitExamApiV1ExamsExamIdAttemptsPostResponse = (ExamResultResponse);

export type SubmitExamApiV1ExamsExamIdAttemptsPostError = (HTTPValidationError);

export type SubmitDiagnosticApiV1DiagnosticsInstrumentIdAttemptsPostData = {
    body: DiagnosticSubmission;
    path: {
        instrument_id: string;
    };
};

export type SubmitDiagnosticApiV1DiagnosticsInstrumentIdAttemptsPostResponse = (DiagnosticResultResponse);

export type SubmitDiagnosticApiV1DiagnosticsInstrumentIdAttemptsPostError = (HTTPValidationError);

export type GetMyProgressApiV1ProgressGetResponse = (ProgressResponse);

export type GetMyProgressApiV1ProgressGetError = unknown;

export type GetUserProgressApiV1UsersUserIdProgressGetData = {
    path: {
        user_id: string;
    };
};

export type GetUserProgressApiV1UsersUserIdProgressGetResponse = (ProgressResponse);

export type GetUserProgressApiV1UsersUserIdProgressGetError = (HTTPValidationError);
