// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * DiagnosticDetail
 *
 * A diagnostic instrument with its items, served before submission.
 */
export type DiagnosticDetail = {
    /**
     * Id
     */
    id: string;
    /**
     * Course
     */
    course: string;
    /**
     * Kind
     */
    kind: string;
    /**
     * Role
     */
    role: string;
    /**
     * Instructions
     */
    instructions: string;
    /**
     * Items
     */
    items: Array<DiagnosticItemRead>;
};

/**
 * DiagnosticItemRead
 *
 * A diagnostic item served before submission (no answer key).
 *
 * ``manual`` is exposed so the runner knows which items are self-marked;
 * ``answer`` / ``v`` / ``accept`` are intentionally absent.
 */
export type DiagnosticItemRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Section Title
     */
    section_title: string;
    /**
     * Label
     */
    label: string;
    /**
     * Prompt
     */
    prompt: string;
    /**
     * Manual
     */
    manual: boolean;
};

/**
 * DiagnosticItemReview
 *
 * One item's post-submission review (answer revealed here).
 */
export type DiagnosticItemReview = {
    /**
     * Item Id
     */
    item_id: string;
    /**
     * Correct
     */
    correct: boolean;
    /**
     * Manual
     */
    manual: boolean;
    /**
     * Answer
     */
    answer: string;
};

/**
 * DiagnosticResultResponse
 *
 * The graded result of a diagnostic submission.
 */
export type DiagnosticResultResponse = {
    /**
     * Attempt Id
     */
    attempt_id: string;
    /**
     * Passed
     */
    passed: boolean;
    /**
     * Verdict
     */
    verdict: string;
    /**
     * Correct
     */
    correct: number;
    /**
     * Total
     */
    total: number;
    /**
     * Summary
     */
    summary: string;
    /**
     * Group Scores
     */
    group_scores?: {
        [key: string]: number;
    };
    /**
     * Review
     */
    review?: Array<DiagnosticItemReview>;
};

/**
 * DiagnosticSubmission
 *
 * A student's diagnostic submission.
 *
 * Attributes:
 * responses: Item id -> raw typed answer (for auto-graded items).
 * marks: Item id -> bool, the student's self-marks for manual items.
 * elapsed_sec: Seconds spent before submission.
 */
export type DiagnosticSubmission = {
    /**
     * Responses
     */
    responses?: {
        [key: string]: string;
    };
    /**
     * Marks
     */
    marks?: {
        [key: string]: boolean;
    };
    /**
     * Elapsed Sec
     */
    elapsed_sec?: number;
};

/**
 * DiagnosticSummary
 *
 * A diagnostic instrument in a catalog listing (no items).
 */
export type DiagnosticSummary = {
    /**
     * Id
     */
    id: string;
    /**
     * Course
     */
    course: string;
    /**
     * Kind
     */
    kind: string;
    /**
     * Role
     */
    role: string;
};

/**
 * ExamDetail
 *
 * An exam with its problems, served before submission (no answer key).
 */
export type ExamDetail = {
    /**
     * Id
     */
    id: string;
    /**
     * Contest
     */
    contest: string;
    /**
     * Year
     */
    year: number;
    /**
     * Variant
     */
    variant: string;
    /**
     * Duration Sec
     */
    duration_sec: number;
    /**
     * Score Mode
     */
    score_mode: string;
    /**
     * Num Problems
     */
    num_problems: number;
    /**
     * Voided
     */
    voided: Array<number>;
    /**
     * Problems
     */
    problems: Array<ProblemRead>;
};

/**
 * ExamResultResponse
 *
 * The graded result of an exam submission.
 */
export type ExamResultResponse = {
    /**
     * Attempt Id
     */
    attempt_id: string;
    /**
     * Score
     */
    score: number;
    /**
     * Max Score
     */
    max_score: number;
    /**
     * Correct
     */
    correct: number;
    /**
     * Wrong
     */
    wrong: number;
    /**
     * Blank
     */
    blank: number;
    /**
     * Review
     */
    review: Array<ReviewItemResponse>;
};

/**
 * ExamSubmission
 *
 * A student's exam submission.
 */
export type ExamSubmission = {
    /**
     * Answers
     */
    answers: Array<string | null>;
    /**
     * Flags
     */
    flags?: Array<boolean>;
    /**
     * Time Used Sec
     */
    time_used_sec?: number;
};

/**
 * ExamSummary
 *
 * An exam in a catalog listing (no problems).
 */
export type ExamSummary = {
    /**
     * Id
     */
    id: string;
    /**
     * Contest
     */
    contest: string;
    /**
     * Year
     */
    year: number;
    /**
     * Variant
     */
    variant: string;
    /**
     * Duration Sec
     */
    duration_sec: number;
    /**
     * Score Mode
     */
    score_mode: string;
    /**
     * Num Problems
     */
    num_problems: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthStatus
 *
 * Health check response model.
 */
export type HealthStatus = {
    /**
     * Status
     *
     * Overall status: ok, degraded, or error
     */
    status: string;
    /**
     * Timestamp
     *
     * Unix timestamp
     */
    timestamp?: number;
    /**
     * Uptime Seconds
     *
     * Application uptime in seconds
     */
    uptime_seconds: number;
    /**
     * Version
     *
     * Application version
     */
    version?: string;
    /**
     * Python Version
     */
    python_version?: string;
};

/**
 * InviteCreateRequest
 *
 * Request to mint a one-time invite (coach/admin only).
 */
export type InviteCreateRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Role
     */
    role?: string;
};

/**
 * InviteCreatedResponse
 *
 * The freshly minted invite; ``token`` is shown exactly once.
 */
export type InviteCreatedResponse = {
    /**
     * Token
     */
    token: string;
    /**
     * Email
     */
    email: string;
    /**
     * Role
     */
    role: string;
};

/**
 * InviteValidationResponse
 *
 * Public validation result for an invite token.
 */
export type InviteValidationResponse = {
    /**
     * Valid
     */
    valid: boolean;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Role
     */
    role?: string | null;
};

/**
 * LoginRequest
 *
 * Credentials for starting a session.
 */
export type LoginRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * ProblemRead
 *
 * A problem as served before submission.
 *
 * Note the deliberate absence of any ``correct_answer`` field.
 */
export type ProblemRead = {
    /**
     * Number
     */
    number: number;
    /**
     * Render Mode
     */
    render_mode: string;
    /**
     * Body Latex
     */
    body_latex?: string | null;
    /**
     * Image Path
     */
    image_path?: string | null;
    /**
     * Choices
     */
    choices?: Array<{
        [key: string]: unknown;
    }> | null;
};

/**
 * ProgressResponse
 *
 * A user's combined progress and recommendation.
 */
export type ProgressResponse = {
    /**
     * Test Attempts
     */
    test_attempts: Array<unknown>;
    /**
     * Diagnostic Attempts
     */
    diagnostic_attempts: Array<unknown>;
    /**
     * Recommendation Course
     */
    recommendation_course: string | null;
    /**
     * Recommendation Reason
     */
    recommendation_reason: string;
    /**
     * Unlocked By Amc
     */
    unlocked_by_amc?: Array<string>;
    /**
     * Algebra Warning
     */
    algebra_warning?: string | null;
};

/**
 * ReadinessCheck
 *
 * Individual dependency check result.
 */
export type ReadinessCheck = {
    /**
     * Name
     *
     * Dependency name
     */
    name: string;
    /**
     * Status
     *
     * Check passed
     */
    status: boolean;
    /**
     * Latency Ms
     *
     * Check latency in milliseconds
     */
    latency_ms?: number | null;
    /**
     * Error
     *
     * Error message if failed
     */
    error?: string | null;
};

/**
 * ReadinessStatus
 *
 * Readiness check response with dependency details.
 */
export type ReadinessStatus = {
    /**
     * Status
     *
     * Overall status: ok, degraded, or error
     */
    status: string;
    /**
     * Timestamp
     *
     * Unix timestamp
     */
    timestamp?: number;
    /**
     * Uptime Seconds
     *
     * Application uptime in seconds
     */
    uptime_seconds: number;
    /**
     * Version
     *
     * Application version
     */
    version?: string;
    /**
     * Python Version
     */
    python_version?: string;
    /**
     * Checks
     *
     * Individual dependency checks
     */
    checks?: {
        [key: string]: ReadinessCheck;
    };
};

/**
 * RegisterRequest
 *
 * Invite redemption: set a password and create the account.
 */
export type RegisterRequest = {
    /**
     * Token
     */
    token: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Password
     */
    password: string;
};

/**
 * ReviewItemResponse
 *
 * One problem's post-submission review (answer key revealed here).
 */
export type ReviewItemResponse = {
    /**
     * N
     */
    n: number;
    /**
     * Your
     */
    your: string | null;
    /**
     * Correct
     */
    correct: string;
    /**
     * Ok
     */
    ok: boolean;
    /**
     * Voided
     */
    voided: boolean;
};

/**
 * UserResponse
 *
 * A user, safe to return to the authenticated client.
 */
export type UserResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Role
     */
    role: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type LivenessHealthLiveGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/live';
};

export type LivenessHealthLiveGetResponses = {
    /**
     * Successful Response
     */
    200: HealthStatus;
};

export type LivenessHealthLiveGetResponse = LivenessHealthLiveGetResponses[keyof LivenessHealthLiveGetResponses];

export type ReadinessHealthReadyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/ready';
};

export type ReadinessHealthReadyGetErrors = {
    /**
     * Application is not ready (dependencies unavailable)
     */
    503: unknown;
};

export type ReadinessHealthReadyGetResponses = {
    /**
     * Application is ready to serve traffic
     */
    200: ReadinessStatus;
};

export type ReadinessHealthReadyGetResponse = ReadinessHealthReadyGetResponses[keyof ReadinessHealthReadyGetResponses];

export type StartupHealthStartupGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/startup';
};

export type StartupHealthStartupGetResponses = {
    /**
     * Successful Response
     */
    200: HealthStatus;
};

export type StartupHealthStartupGetResponse = StartupHealthStartupGetResponses[keyof StartupHealthStartupGetResponses];

export type LoginApiV1AuthLoginPostData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginApiV1AuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiV1AuthLoginPostError = LoginApiV1AuthLoginPostErrors[keyof LoginApiV1AuthLoginPostErrors];

export type LoginApiV1AuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type LoginApiV1AuthLoginPostResponse = LoginApiV1AuthLoginPostResponses[keyof LoginApiV1AuthLoginPostResponses];

export type LogoutApiV1AuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutApiV1AuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutApiV1AuthLogoutPostResponse = LogoutApiV1AuthLogoutPostResponses[keyof LogoutApiV1AuthLogoutPostResponses];

export type MeApiV1AuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type MeApiV1AuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type MeApiV1AuthMeGetResponse = MeApiV1AuthMeGetResponses[keyof MeApiV1AuthMeGetResponses];

export type RegisterApiV1AuthRegisterPostData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type RegisterApiV1AuthRegisterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterApiV1AuthRegisterPostError = RegisterApiV1AuthRegisterPostErrors[keyof RegisterApiV1AuthRegisterPostErrors];

export type RegisterApiV1AuthRegisterPostResponses = {
    /**
     * Successful Response
     */
    201: UserResponse;
};

export type RegisterApiV1AuthRegisterPostResponse = RegisterApiV1AuthRegisterPostResponses[keyof RegisterApiV1AuthRegisterPostResponses];

export type ValidateInviteApiV1AuthInvitesTokenGetData = {
    body?: never;
    path: {
        /**
         * Token
         */
        token: string;
    };
    query?: never;
    url: '/api/v1/auth/invites/{token}';
};

export type ValidateInviteApiV1AuthInvitesTokenGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ValidateInviteApiV1AuthInvitesTokenGetError = ValidateInviteApiV1AuthInvitesTokenGetErrors[keyof ValidateInviteApiV1AuthInvitesTokenGetErrors];

export type ValidateInviteApiV1AuthInvitesTokenGetResponses = {
    /**
     * Successful Response
     */
    200: InviteValidationResponse;
};

export type ValidateInviteApiV1AuthInvitesTokenGetResponse = ValidateInviteApiV1AuthInvitesTokenGetResponses[keyof ValidateInviteApiV1AuthInvitesTokenGetResponses];

export type CreateInviteApiV1InvitesPostData = {
    body: InviteCreateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/invites';
};

export type CreateInviteApiV1InvitesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateInviteApiV1InvitesPostError = CreateInviteApiV1InvitesPostErrors[keyof CreateInviteApiV1InvitesPostErrors];

export type CreateInviteApiV1InvitesPostResponses = {
    /**
     * Successful Response
     */
    201: InviteCreatedResponse;
};

export type CreateInviteApiV1InvitesPostResponse = CreateInviteApiV1InvitesPostResponses[keyof CreateInviteApiV1InvitesPostResponses];

export type ListExamsApiV1ExamsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Contest
         */
        contest?: string | null;
    };
    url: '/api/v1/exams';
};

export type ListExamsApiV1ExamsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListExamsApiV1ExamsGetError = ListExamsApiV1ExamsGetErrors[keyof ListExamsApiV1ExamsGetErrors];

export type ListExamsApiV1ExamsGetResponses = {
    /**
     * Response List Exams Api V1 Exams Get
     *
     * Successful Response
     */
    200: Array<ExamSummary>;
};

export type ListExamsApiV1ExamsGetResponse = ListExamsApiV1ExamsGetResponses[keyof ListExamsApiV1ExamsGetResponses];

export type GetExamApiV1ExamsExamIdGetData = {
    body?: never;
    path: {
        /**
         * Exam Id
         */
        exam_id: string;
    };
    query?: never;
    url: '/api/v1/exams/{exam_id}';
};

export type GetExamApiV1ExamsExamIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetExamApiV1ExamsExamIdGetError = GetExamApiV1ExamsExamIdGetErrors[keyof GetExamApiV1ExamsExamIdGetErrors];

export type GetExamApiV1ExamsExamIdGetResponses = {
    /**
     * Successful Response
     */
    200: ExamDetail;
};

export type GetExamApiV1ExamsExamIdGetResponse = GetExamApiV1ExamsExamIdGetResponses[keyof GetExamApiV1ExamsExamIdGetResponses];

export type ListDiagnosticsApiV1DiagnosticsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/diagnostics';
};

export type ListDiagnosticsApiV1DiagnosticsGetResponses = {
    /**
     * Response List Diagnostics Api V1 Diagnostics Get
     *
     * Successful Response
     */
    200: Array<DiagnosticSummary>;
};

export type ListDiagnosticsApiV1DiagnosticsGetResponse = ListDiagnosticsApiV1DiagnosticsGetResponses[keyof ListDiagnosticsApiV1DiagnosticsGetResponses];

export type GetDiagnosticApiV1DiagnosticsInstrumentIdGetData = {
    body?: never;
    path: {
        /**
         * Instrument Id
         */
        instrument_id: string;
    };
    query?: never;
    url: '/api/v1/diagnostics/{instrument_id}';
};

export type GetDiagnosticApiV1DiagnosticsInstrumentIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDiagnosticApiV1DiagnosticsInstrumentIdGetError = GetDiagnosticApiV1DiagnosticsInstrumentIdGetErrors[keyof GetDiagnosticApiV1DiagnosticsInstrumentIdGetErrors];

export type GetDiagnosticApiV1DiagnosticsInstrumentIdGetResponses = {
    /**
     * Successful Response
     */
    200: DiagnosticDetail;
};

export type GetDiagnosticApiV1DiagnosticsInstrumentIdGetResponse = GetDiagnosticApiV1DiagnosticsInstrumentIdGetResponses[keyof GetDiagnosticApiV1DiagnosticsInstrumentIdGetResponses];

export type SubmitExamApiV1ExamsExamIdAttemptsPostData = {
    body: ExamSubmission;
    path: {
        /**
         * Exam Id
         */
        exam_id: string;
    };
    query?: never;
    url: '/api/v1/exams/{exam_id}/attempts';
};

export type SubmitExamApiV1ExamsExamIdAttemptsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubmitExamApiV1ExamsExamIdAttemptsPostError = SubmitExamApiV1ExamsExamIdAttemptsPostErrors[keyof SubmitExamApiV1ExamsExamIdAttemptsPostErrors];

export type SubmitExamApiV1ExamsExamIdAttemptsPostResponses = {
    /**
     * Successful Response
     */
    200: ExamResultResponse;
};

export type SubmitExamApiV1ExamsExamIdAttemptsPostResponse = SubmitExamApiV1ExamsExamIdAttemptsPostResponses[keyof SubmitExamApiV1ExamsExamIdAttemptsPostResponses];

export type SubmitDiagnosticApiV1DiagnosticsInstrumentIdAttemptsPostData = {
    body: DiagnosticSubmission;
    path: {
        /**
         * Instrument Id
         */
        instrument_id: string;
    };
    query?: never;
    url: '/api/v1/diagnostics/{instrument_id}/attempts';
};

export type SubmitDiagnosticApiV1DiagnosticsInstrumentIdAttemptsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubmitDiagnosticApiV1DiagnosticsInstrumentIdAttemptsPostError = SubmitDiagnosticApiV1DiagnosticsInstrumentIdAttemptsPostErrors[keyof SubmitDiagnosticApiV1DiagnosticsInstrumentIdAttemptsPostErrors];

export type SubmitDiagnosticApiV1DiagnosticsInstrumentIdAttemptsPostResponses = {
    /**
     * Successful Response
     */
    200: DiagnosticResultResponse;
};

export type SubmitDiagnosticApiV1DiagnosticsInstrumentIdAttemptsPostResponse = SubmitDiagnosticApiV1DiagnosticsInstrumentIdAttemptsPostResponses[keyof SubmitDiagnosticApiV1DiagnosticsInstrumentIdAttemptsPostResponses];

export type GetMyProgressApiV1ProgressGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/progress';
};

export type GetMyProgressApiV1ProgressGetResponses = {
    /**
     * Successful Response
     */
    200: ProgressResponse;
};

export type GetMyProgressApiV1ProgressGetResponse = GetMyProgressApiV1ProgressGetResponses[keyof GetMyProgressApiV1ProgressGetResponses];

export type GetUserProgressApiV1UsersUserIdProgressGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}/progress';
};

export type GetUserProgressApiV1UsersUserIdProgressGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserProgressApiV1UsersUserIdProgressGetError = GetUserProgressApiV1UsersUserIdProgressGetErrors[keyof GetUserProgressApiV1UsersUserIdProgressGetErrors];

export type GetUserProgressApiV1UsersUserIdProgressGetResponses = {
    /**
     * Successful Response
     */
    200: ProgressResponse;
};

export type GetUserProgressApiV1UsersUserIdProgressGetResponse = GetUserProgressApiV1UsersUserIdProgressGetResponses[keyof GetUserProgressApiV1UsersUserIdProgressGetResponses];
