"""initial schema

Revision ID: d8e219f529db
Revises: 
Create Date: 2026-05-31 18:42:53.202029

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d8e219f529db"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("diagnostic_instruments",
    sa.Column("id", sa.String(length=64), nullable=False),
    sa.Column("course", sa.String(length=120), nullable=False),
    sa.Column("kind", sa.String(length=40), nullable=False),
    sa.Column("role", sa.String(length=8), nullable=False),
    sa.Column("ladder", sa.JSON(), nullable=False),
    sa.Column("grading", sa.JSON(), nullable=False),
    sa.Column("instructions", sa.String(), nullable=False),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_table("exams",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("contest", sa.String(length=20), nullable=False),
    sa.Column("year", sa.Integer(), nullable=False),
    sa.Column("variant", sa.String(length=2), nullable=False),
    sa.Column("duration_sec", sa.Integer(), nullable=False),
    sa.Column("score_mode", sa.String(length=20), nullable=False),
    sa.Column("num_problems", sa.Integer(), nullable=False),
    sa.Column("voided", sa.JSON(), nullable=False),
    sa.Column("source_url", sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("contest", "year", "variant", name="uq_exam_identity")
    )
    op.create_index(op.f("ix_exams_contest"), "exams", ["contest"], unique=False)
    op.create_table("users",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("email", sa.String(length=320), nullable=False),
    sa.Column("display_name", sa.String(length=200), nullable=False),
    sa.Column("role", sa.String(length=20), nullable=False),
    sa.Column("password_hash", sa.String(length=255), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table("diagnostic_attempts",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("user_id", sa.Uuid(), nullable=False),
    sa.Column("instrument_id", sa.String(length=64), nullable=False),
    sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("responses", sa.JSON(), nullable=False),
    sa.Column("marks", sa.JSON(), nullable=False),
    sa.Column("passed", sa.Boolean(), nullable=False),
    sa.Column("verdict", sa.String(length=8), nullable=False),
    sa.Column("summary", sa.String(), nullable=False),
    sa.Column("elapsed_sec", sa.Integer(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(["instrument_id"], ["diagnostic_instruments.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_diagnostic_attempts_instrument_id"), "diagnostic_attempts", ["instrument_id"], unique=False)
    op.create_index(op.f("ix_diagnostic_attempts_user_id"), "diagnostic_attempts", ["user_id"], unique=False)
    op.create_table("diagnostic_items",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("instrument_id", sa.String(length=64), nullable=False),
    sa.Column("section_title", sa.String(length=200), nullable=False),
    sa.Column("label", sa.String(length=40), nullable=False),
    sa.Column("prompt", sa.String(), nullable=False),
    sa.Column("answer", sa.String(), nullable=False),
    sa.Column("numeric_value", sa.Float(), nullable=True),
    sa.Column("accept", sa.JSON(), nullable=False),
    sa.Column("group", sa.String(length=8), nullable=True),
    sa.Column("manual", sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(["instrument_id"], ["diagnostic_instruments.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_diagnostic_items_instrument_id"), "diagnostic_items", ["instrument_id"], unique=False)
    op.create_table("invites",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("token_hash", sa.String(length=64), nullable=False),
    sa.Column("email", sa.String(length=320), nullable=False),
    sa.Column("role", sa.String(length=20), nullable=False),
    sa.Column("created_by", sa.Uuid(), nullable=True),
    sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("redeemed_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_invites_email"), "invites", ["email"], unique=False)
    op.create_index(op.f("ix_invites_token_hash"), "invites", ["token_hash"], unique=True)
    op.create_table("problems",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("exam_id", sa.Uuid(), nullable=False),
    sa.Column("number", sa.Integer(), nullable=False),
    sa.Column("render_mode", sa.String(length=10), nullable=False),
    sa.Column("body_latex", sa.String(), nullable=True),
    sa.Column("image_path", sa.String(length=500), nullable=True),
    sa.Column("choices", sa.JSON(), nullable=True),
    sa.Column("correct_answer", sa.String(length=1), nullable=False),
    sa.Column("solution_url", sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(["exam_id"], ["exams.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("exam_id", "number", name="uq_problem_number")
    )
    op.create_index(op.f("ix_problems_exam_id"), "problems", ["exam_id"], unique=False)
    op.create_table("sessions",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("user_id", sa.Uuid(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("revoked", sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table("test_attempts",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("user_id", sa.Uuid(), nullable=False),
    sa.Column("exam_id", sa.Uuid(), nullable=False),
    sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("answers", sa.JSON(), nullable=False),
    sa.Column("flags", sa.JSON(), nullable=False),
    sa.Column("time_used_sec", sa.Integer(), nullable=False),
    sa.Column("score", sa.Float(), nullable=False),
    sa.Column("correct", sa.Integer(), nullable=False),
    sa.Column("wrong", sa.Integer(), nullable=False),
    sa.Column("blank", sa.Integer(), nullable=False),
    sa.Column("max_score", sa.Float(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(["exam_id"], ["exams.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_test_attempts_exam_id"), "test_attempts", ["exam_id"], unique=False)
    op.create_index(op.f("ix_test_attempts_user_id"), "test_attempts", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_test_attempts_user_id"), table_name="test_attempts")
    op.drop_index(op.f("ix_test_attempts_exam_id"), table_name="test_attempts")
    op.drop_table("test_attempts")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_problems_exam_id"), table_name="problems")
    op.drop_table("problems")
    op.drop_index(op.f("ix_invites_token_hash"), table_name="invites")
    op.drop_index(op.f("ix_invites_email"), table_name="invites")
    op.drop_table("invites")
    op.drop_index(op.f("ix_diagnostic_items_instrument_id"), table_name="diagnostic_items")
    op.drop_table("diagnostic_items")
    op.drop_index(op.f("ix_diagnostic_attempts_user_id"), table_name="diagnostic_attempts")
    op.drop_index(op.f("ix_diagnostic_attempts_instrument_id"), table_name="diagnostic_attempts")
    op.drop_table("diagnostic_attempts")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_exams_contest"), table_name="exams")
    op.drop_table("exams")
    op.drop_table("diagnostic_instruments")
    # ### end Alembic commands ###
